name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease # for debug app uncommit replace this with assembleRelease run: ./gradlew assembleDebug

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
            -PstorePassword="${{ secrets.STORE_PASSWORD }}" \
            -PkeyAlias="${{ secrets.KEY_ALIAS }}" \
            -PkeyPassword="${{ secrets.KEY_PASSWORD }}"